### ISSUE TITLE
special characers not exported properly from google sheet

### ISSUE THREAD

**Issue by hxrts** [guild-is/guild.is#10]
`2018 0xÎ© Matt Liston, Avery Singer`

`2017 Ã˜x Sam Hart, Lars TCF Holdhus, Melanie Hoff, Rob Myers, Nora Khan, Simon Denny, FOAM`

`2015 Ã…zone Futures Market VA`

**Comment by clevinson** [comment]
hm...  Seems to work fine on my mac. Maybe it's an issue with browser or OS ?
![Screen Shot 2019-05-27 at 12 06 05 PM](https://user-images.githubusercontent.com/832188/58412970-eb615980-8077-11e9-8eac-fc59b00fad9f.png)

**Comment by clevinson** [comment]
@hxrts just checked on firefox, and works fine for me there as well...

**Comment by hxrts** [comment]
ok, that's good. can you check if it works on netlify?
