### ISSUE TITLE
newsletter signup doesn't work 

### ISSUE THREAD

**Issue by okwme** [guild-is/guild.is#3]
👹

**Comment by keikreutler** [comment]
hello darkness my old friend

**Comment by louiscenter** [comment]
hell👹 darkness my 👹ld friend

**Comment by hxrts** [comment]
do we pick a newsletter service? also still waiting on Mat to fork over the DNS.

**Comment by hxrts** [comment]
this now works in the mailchimp branch. styling still needs a little more work

**Comment by hxrts** [comment]
fixed in latest PR
